name: Build & Deploy to GitHub Pages (conditional)

on:
  push:
    branches: [ main ]

# Only proceed when the HEAD commit message begins with "DEPLOY"
# Usage example:  git commit -m "DEPLOY: publish latest changes" && git push

permissions:
  contents: read
  pages: write      # to deploy with official Pages action
  id-token: write   # to authenticate for Pages deployment

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  build:
    if: startsWith(github.event.head_commit.message, 'DEPLOY')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    if: startsWith(github.event.head_commit.message, 'DEPLOY')
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
